### ISSUE TITLE
Allow "inline" violation reports to contain the text of offending scripts

### ISSUE THREAD

**Issue by arturjanc** [w3c/webappsec-csp#119]
One of the biggest problems with CSP violation reports is the large number of false positives. Popular applications, even if they are compatible with their CSP, can generate hundreds of QPS of violation reports, usually due to markup injected by browser extensions. The amount of noise makes it very difficult to find breakage caused by deploying CSP in a production environment.

Ideally, this would be solved by recognizing all modifications to the page introduced by extensions, and have these modifications exempt from CSP; in practice, this seems like an intractable -- or at least very difficult -- problem for user agents. There are probably ways to indicate to authors that one of their pages violates its CSP without having to solve the extension-injected markup issue...

CSP3 currently requires violations caused by inline markup to have a blocked-uri of "inline". This is better than in the past, but it leads to a lot of `"inline"` violations without any identifying information. For nonce-based policies with `'strict-dynamic'` this is by far the most common violation type. The blocked resource is `"inline"` for event handlers, javascript: URIs, and inline scripts without a nonce; the only exception are external scripts without a nonce, but they are easy to identify by the `blocked-uri`.

**Proposal**: For "inline" violations, the UA could include additional information in the report to identify the offending inline markup and help developers distinguish site problems from extension-generated violations. It could be enabled via a new keyword in the `report-uri` directive, e.g. `include-inline-script-details` (as usual, terrible name).

There are several approaches that might work:
- Include the entire offending script (e.g. `<b onclick="foo('bar')">` and `<script>foo('bar')</script>` would both return `foo('bar')`.
- Include a fixed-length prefix of the script (10 bytes? 50 bytes?). This sounds awkward, but in practice it should allow developers to search their codebase for the given string and/or build databases of common false extension-generated false positives.
- Perform more elaborate processing of the script text, e.g. replace string/integer values with placeholders, find the first named function and return its name, etc. These are even more awkward and probably non-starters, but in principle there's nothing that would prohibit the UA from doing some processing on the script text to reduce the amount of information it sends but still make the report useful to the developer.

I can think of two things that we'd need to be careful about:
- Disclosing script contents shouldn't allow CSP to be used as a mechanism to leak data across origins. I think the proposal is okay since it's limited to inline scripts, and the document can already inspect all its inline markup, but we should think carefully about this.
- Sending full script contents to third-party collector infrastructure could leak sensitive data. The opt-in keyword in report-uri should solve this concern.

Overall, this is something where the simplicity of implementation in user agents might trump other concerns, i.e. even a non-ideal mechanism that gives _some_ information to developers to help them decide if a violation report is legitimate would still be quite helpful.

**Comment by arturjanc** [comment]
Directly spam^Wadding some people who might care: @mikewest @dveditz @hillbrad @devd @mikispag

**Comment by arturjanc** [comment]
@devd helpfully pointed out that something like this already exists in Firefox (!) -- it's the 'script-sample' field: 
https://www.tollmanz.com/content-security-policy-report-samples/
https://github.com/w3c/webappsec-csp/issues/81

A main missing piece of the FF implementation is that while 'script-sample' sends contents of inline scripts, it doesn't do the same for event handlers or javascript: URIs; for event handlers, the value is something like "script-sample":"onmouseover attribute on H1 element", and for javascript: URIs there is no "script-sample" at all. But if "script-sample" also included the contents of the event handler, it would probably be good enough...

Also, since FF has already included script snippets in violation reports, this probably removes the need for an additional keyword to enable this change ;-)

**Comment by mikewest** [comment]
Yes. Firefox ships this for inline and external scripts, despite some conversations where I thought we agreed that they'd stop. :)

Basically, the concern we've had in the past has been the unintentional leakage of cross-origin data that you highlight at the bottom of your comments above. We sanitize error messages for third-party JavaScript delivered without `crossorigin` opt-in for good reason, and it's not clear to me that it's safe to stop doing so just because Firefox is shipping that behavior. Moreover, the fact that browsers are bad at allowing extension scripts to execute doesn't seem like a good reason to give reporting endpoints even more detail about which extensions a user has installed.

That said, coming up with a safe way of sharing data with a reporting endpoint seems reasonable. To that end:

1. Returning the entire inline script seems like a bad idea, as it's likely to contain things like `var oAuthToken = [sekrit]` which would be bad to log forever.

2. A fixed-length prefix seems like the right direction to explore. An even safer variant would be a hash of a prefix (or the whole script, I suppose).

3. @jeisinger might know more about what data we actually have in a stack trace for things like violations that trace back to `fetch()`.

**Comment by arturjanc** [comment]
I'm not sure we need to settle this question, but I'm curious about the risk of doing this. Is the problem that evil.com could do something like `<script src='//victim.com/page.html'>` and exfiltrate data from the page using the violation report?

It seems like this can be resolved by only doing this for inline scripts. I think that by definition it means that the markup is directly present in the current document, so the document can already inspect it? But I'm curious if there are any problems that I'm not thinking about...

Re: sending a hash, it's appealing for some reasons, but it wouldn't solve the main problem which is the inability to find the offending markup based on a violation report. At least I can't think of a way to make a hash very useful in this context.

Perhaps another possibility would be to do some transformation of the script text, such as removing contents of strings, but that's probably overkill... Some limited-length prefix might actually be the most sane approach.

**Comment by mikewest** [comment]
Started poking at this in https://github.com/w3c/webappsec-csp/commit/e3939cadb89c3bac1186a1bd806c1aae622417f5 and https://github.com/w3c/webappsec-csp/commit/d1d868eabac4e300d34dbefcfe6b01c12e3cee9e (and https://codereview.chromium.org/2436003002). Copy/pasting from the commit:

---

Firefox has shipped a 'script-sample' property in CSP violation reports
since their initial implementation, while other browsers have resisted
doing the same. This patch attempts to reach concensus on an opt-in
variant Firefox's behavior. In short, we'll collect a 40-character
sample for inline script and style violations, and include it in the
violation report (and associated SecurityPolicyViolationEvent object)
iff a `'report-sample'` expression is present in the violated directive.
That is, given:

    script-src 'nonce-abc' 'report-sample'

and:

    <script>alert(1);</script>

The violation report would include:

    {
      ...
      "sample": "alert(1);"
    }

**Comment by mikewest** [comment]
@ckerschb, @dveditz, @mozfreddyb: Would y'all be willing to align Firefox's shipping implementation with this proposal over time? Basically, rename (copy?) `script-sample` to `sample`, make the latter opt-in with the `'report-sample'` expression, and add sampling for style elements/attributes. WDYT?

**Comment by devd** [comment]
There is already code in Firefox and in report collectors all over the world relying on this schema. Whats the risk we are worried about here? I am not a fan of breaking all this code unless there is a significant security risk.

**Comment by mikewest** [comment]
We could have `script-sample` and `style-sample`, I suppose. Or have `script-sample` contain things other than samples of scripts. Both of those seem like a bad place to end up, though.

I'm not at all suggesting that Firefox turn off `script-sample` tomorrow, I agree that that would make developers sad. Instead, I'm suggesting that they deprecate that and move to a more generic name over time.

**Comment by devd** [comment]
Has there been much demand for style-sample?

**Comment by jacobbednarz** [comment]
> We could have script-sample and style-sample, I suppose. Or have script-sample contain things other than samples of scripts. Both of those seem like a bad place to end up, though.

Would this ever need to extend to other directives? I think if it's only ever going to be two "sample" fields, we can probably get away with bolting on another. One of the problems this creates is that you need to have logic in your filtering mechanism to work out which one to accept.

> Has there been much demand for style-sample?

Without the `script-sample` field, some violation reports are just useless. I'm not completely certain this will change when receiving `style` violations since they can be used in similar use cases.

As an ideal solution I'd like to see a consolidated field that was globally just for the sample data an remove the need to do additionally logic in your filtering.

**Comment by mikewest** [comment]
@devd:
> Has there been much demand for style-sample?

Not from Google folks, as they don't use `style-src`. If they decided tomorrow that they needed `style-src`, I am pretty confident that their next step would be filling my inbox with requests for samples. :)

It doesn't make much sense to me to single out one use-case when we have the data lying around in both the spec and implementation to service another.

@jacobbednarz:
> As an ideal solution I'd like to see a consolidated field that was globally just for the sample data an remove the need to do additionally logic in your filtering.

That's my current proposal.

**Comment by mikewest** [comment]
It occurs to me that @scotthelme might also have informed opinions about demand.

**Comment by shekyan** [comment]
@mattrobenolt might have some opinions on this as well.

**Comment by jacobbednarz** [comment]
Apologies @mikewest, my update should have included something along the lines of "+1 to Mike's proposal 😛 " as well since reading it back now looks like that intention could have been missed.

**Comment by ScottHelme** [comment]
Filtering on `script-sample` would certainly allow me to ditch a lot of redundant reports, I don't have the functionality right now because the field isn't widely provided by browsers.

I do agree that moving to a generic `sample` field would alleviate complexity for me and most likely, by extension, anyone else running a CSP collection endpoint.

**Comment by mozfreddyb** [comment]
> @ckerschb, @dveditz, @mozfreddyb: Would y'all be willing to align Firefox's shipping implementation with this proposal over time? Basically, rename (copy?) script-sample to sample, make the latter opt-in with the 'report-sample' expression, and add sampling for style elements/attributes. WDYT?

It's unlikely we'll jump on this any time soon, given we already have `script-sample`.

**Comment by mikewest** [comment]
> It's unlikely we'll jump on this any time soon, given we already have `script-sample`.

Is that a question of resource allocation, or a fundamental disagreement about the model I'm proposing?

**Comment by mozfreddyb** [comment]
Well, `script-sample` works (to a certain extent :)).
But it's more a question of prioritization.

**Comment by lweichselbaum** [comment]
@mozfreddyb Do you think FF could (maybe soonisch) include a sample of the offending script also for event-handlers?
This facet of the new script sample proposal would be extremely valuable for developers. Currently it is not feasible to distinguish between an event-handler script violation caused by an extension or by the site itself.
So we end up with a high number of violations were we just don't have the information we'd need to classify them as noise/real...

**Comment by mozfreddyb** [comment]
No, not anytime soon.
But please do file a bug on us. It looks simple so it *might* be a good starting bug for newcomers to our CSP codebase (having briefly looked at [the code that does CSP event handler stuff](https://dxr.mozilla.org/mozilla-central/source/dom/security/nsCSPContext.cpp#615))

**Comment by mikewest** [comment]
Talked with Artur, basically I think it makes the most sense to change the name of the JSON field in the spec to `script-sample`, and deal with the fact that it will sometimes contain things other than scripts. It's deprecated in favor of `report-to` anyway, and we can serialize it as `sample` there since we're changing the format anyway. I'll also leave it as `sample` in the `securitypolicyviolation` object, which I assume Firefox will implement someday? :)

WDYT?

**Comment by dveditz** [comment]
I understand the desire for script snippets, but if firefox follows this proposal we will lose the information that the violation was an event handler and hints about which one. Is that information not useful at all? is there some way to send both?

**Comment by lweichselbaum** [comment]
That information is somewhat useful, but doesn't allow to differentiate between noise and real violations. While the actual script sample is very useful to find the root cause of a violation. E.g. you can search for the actual code snippet.

I guess sending both is also okay e.g. "onclick attribute on DIV element: foo(bar)".
Or maybe put 'inline', 'inline-script' or 'eval' into blocked-uri (similar to Chrome) to differentiate between eval, inline event handlers and inline scripts.

**Comment by mikewest** [comment]
I don't understand your concern, @dveditz. Firefox ships `script-sample` today, pulling samples from inline scripts, but not event handlers. The proposal in the spec currently does the same in an opt-in fashion, but includes event handlers as well as inline style blocks and attributes (as a consequence of being populated via https://w3c.github.io/webappsec-csp/#should-block-inline).

It seems like an improvement over the status quo from that perspective, and orthogonal to the question of whether we should add hints about where the inline violation occurred.

Related to @lweichselbaum's comment: if y'all want more detail in `blocked-uri` for inline violations, we can trivially change "inline" in step 3.1.3 of https://w3c.github.io/webappsec-csp/#should-block-inline to one of "script", "script attribute", "style", or "style attribute", as that's what we're passing in from HTML. Happy to do that if it's helpful, just file another bug (or point me to the existing bug if I missed it).

**Comment by arturjanc** [comment]
@dveditz My guess is that if we provide the text of the script from an event handler, it will be much more helpful to developers than listing the element name+attribute, to the point that I wouldn't be sad if we completely omitted the latter. Something like `var foo=123; bar(); return baz` is significantly easier to track down than `onload attribute on IMG element`. If you're partial towards keeping the existing information, something like what Lukas suggested above will probably work, at the cost of complicating the snippet format a bit, or introducing inconsistencies between browsers (which is not really a problem for developers, but could be a wart in the spec).

**Comment by mikewest** [comment]
@dveditz: If you'd like to change Firefox's implementation to push sample information and the sample's location (e.g. `onclick attribute on DIV element`) into distinct fields, I'm fine with that. From @mozfreddyb's comments, it sounded like y'all were uninterested in investing time in making any change in the short term.

If that's the case, I'd prefer to just specify that samples go to `script-sample` and be done with it. If you're interested in investing in some changes, then I'm happy to explore other options!

**Comment by mikewest** [comment]
@dveditz: Ping?

I'd like to get this into Chrome 59, which has a branch pretty soon. If y'all don't have a strong opinion, I'd like to run with the suggestion in https://github.com/w3c/webappsec-csp/issues/119#issuecomment-286520087. Do y'all have a strong opinion? @mozfreddyb, @ckerschb?

**Comment by mikewest** [comment]
Ok then. Closing this out via w3c/webappsec-csp@edd5f29. I'll send an intent to ship for Blink shortly.

**Comment by mikewest** [comment]
(Actually closing this out, as per https://github.com/w3c/webappsec-csp/issues/119#issuecomment-288648507)
