### ISSUE TITLE
Does CSP3+Fetch apply to redirects correctly?

### ISSUE THREAD

**Issue by estark37** [w3c/webappsec-csp#134]
(Disclaimer: I might be completely confused, and also might be filing this issue in the wrong place as it might belong better in https://github.com/whatwg/fetch)

My question is: for a request whose redirect mode is 'follow', where do intermediate hops in the redirect chain get checked for CSP?

Fetch checks CSP in two places, both in Main fetch (https://fetch.spec.whatwg.org/#main-fetch):
- Step 5 checks if a request should be blocked
- Step 16 checks if a response should be blocked

Step 5 calls into https://w3c.github.io/webappsec-csp/#should-block-request, which calls various directives' pre-request checks. Pre-request checks generally call into https://w3c.github.io/webappsec-csp/#match-request-to-source-list, which uses `request`'s URL. The URL is the first URL in the request's URL list, thus the initial URL of the request gets checked on each recursive call of main fetch during a redirect, but the intermediate hop URLs do not get checked in step 5.

Step 16 calls into https://w3c.github.io/webappsec-csp/#should-block-response, which calls various directives' post-request checks. Post-request checks generally call into https://w3c.github.io/webappsec-csp/#match-response-to-source-list, which uses `response`'s URL. But at the point that step 16 runs, I think redirects have already been recursively followed (via the step 11 call to HTTP fetch), so in step 16, `response`'s URL will be the final URL that we ended up at. So I don't think step 16 ever checks CSP for intermediate hops in a redirect chain.

Maybe pre-request checks should be using the request's *current* URL, and HTTP-redirect fetch should be checking responses?

cc @annevk

**Comment by anforowicz** [comment]
Let me point out that (IMHO) the importance of checking redirects differs between various CSP directives.  Let me try to illustrate this by comparing frame-src and form-action directives below.

1. frame-src:

  1.1. I assume that frame-src directive mainly protects the parent frame against the threat of embedding a subframe from an unintended origin.

  1.2. To protect against the threat above, in theory only the final URI could be verified by CSP .

  1.3. This is kind of obvious, but let me also point out that frame-src is enforced for the final URI of both *server* redirects and *client* redirects (e.g. via meta refresh and/or window.location).

  1.4. frame-src doesn't look at URIs of frames opened in another window (e.g. because the anchor in a subframe had a target attribute OR was shift-clicked).  Ignoring other windows seems okay, because the parent-subframe relationship is broken when opening a link in a new window (e.g. the new frame cannot try to trick the user into thinking it is a part of the parent frame's UI).  OTOH, in some scenarios window.opener is still populated (e.g. when clicking an anchor with a target attribute, but not when shift-clicking an anchor) so the newly opened frame can still reach into the original parent.

2. form-action:

  2.1. I assume that form-action directive mainly protects form data against the threat of being disclosed to an unintended origin (for example when a hidden form data inside the frame contains an origin-bound secret used for authentication).

  2.2. To protect against the threat above, it is important to start CSP enforcement from the very first http request (for example - verifying only the origin of the final redirect destination would be wrong, because the form data could be already disclosed to an unintended origin in the first http request).

  2.3. It might be desirable to protect form data against disclosure happening *after* the first http request.  We might want to consider the following threats (personally, I see protection against these threats as lower priority than protection against the threat outlined in 2.2 above):

    2.3.1. Threat of disclosing the form-data to intermediate server redirect destinations (e.g. disclosure to b.com if the redirect chain looks like a.com -> b.com -> c.com).  We might want to consider different behavior depending on the type of a server redirect (e.g. http 307 and 308 responses preserve POST data, while other types of redirects don't).

    2.3.2. Threat of disclosing the form-data to destinations reached via client redirect (e.g. redirect triggered via meta refresh and/or window.location).

    2.3.3. Threat of disclosing the form-data via means other than redirection (e.g. tricking the http server from the original form action into emailing the form data to an unintended origin).

  2.4. form-action needs to enforced even if the form action is opened another window (e.g. because the form element had a target attribute OR because the submit button was shift-clicked).  This is because the protected resource is the form data (and the form data will be disclosed to the origin at form action URI regardless of whether the request happens in a new window or not).

**Comment by annevk** [comment]
frame-src and form-action are not applicable to this issue as they go through HTML's navigate.

Request's current URL seems correct, indeed.

Why would you need to check intermediate responses? I thought the response check was mostly for service workers.

**Comment by mikewest** [comment]
Thanks for filing this, @estark37!

> frame-src and form-action are not applicable to this issue as they go through HTML's navigate.

Modulo the bug noted in https://github.com/whatwg/html/issues/2010, I think we're doing the right thing from a spec perspective for `frame-src` and `form-action`.

> Request's current URL seems correct, indeed.

Yup. This looks like me just being confused. I'll fix this.

> Why would you need to check intermediate responses? I thought the response check was mostly for service workers.

I think Anne's right. The only reason we added the response check is to deal with a service worker substituting a blocked resource for an otherwise valid request. That's the only case I know of where a request would be allowed, but its response wouldn't. I'l add some notes to clarify the intent.

That said, `frame-ancestors` might be affected here. I know Blink/WebKit don't currently honor `frame-ancestors` (or `X-Frame-Options`) on redirect responses, but that's something I'd intended to change for Blink in https://codereview.chromium.org/2321503002. As written, I don't think we hook into Fetch at the right spot for that to be effective. I guess I need to check Firefox and Edge behavior to see what we ought to specify here, as the value of blocking redirect responses that don't want to be framed seems low in comparison to the complexity it might introduce.

**Comment by annevk** [comment]
frame-ancestors and X-Frame-Options are again navigate-only concerns I think, no? Or would they also apply to an image load inside a nested browsing context?

**Comment by mikewest** [comment]
> frame-ancestors and X-Frame-Options are again navigate-only concerns I think, no? Or would they also apply to an image load inside a nested browsing context?

Indeed, sorry. `frame-ancestors` used to be a response check. After the recent refactoring you helped me with, it's a "navigation response check" which indeed is part of the navigation algorithm. I think the only "response check" is `sandbox`, which seems reasonable to apply only to the result of a chain of redirects, rather than to each item individually, as we never instantiate a document which we could reasonably sandbox.

**Comment by mikewest** [comment]
Fixed the "current URL" bit in https://github.com/w3c/webappsec-csp/commit/8a88c0cf306b34da6a8fee7cfa574ff9fa34740c. The rest of this is WAI, I believe.
