### ISSUE TITLE
worklet-src directive needed for worklets?

### ISSUE THREAD

**Issue by bfgeek** [w3c/webappsec-csp#203]
[Worklets](https://drafts.css-houdini.org/worklets/) currently use the child-src directive, (same as workers [currently](https://fetch.spec.whatwg.org/#concept-request-destination)). Should there be a worklet-src directive?

**Comment by annevk** [comment]
Workers now have worker-src and also adhere to script-src. I suspect they no longer use child-src. https://w3c.github.io/webappsec-csp/ is a more up-to-date reference. We should revamp that table in Fetch.

**Comment by mikewest** [comment]
As @annevk noted, workers have moved to `worker-src`->`script-src`->`default-src`. Given the capabilities of worklets, it seems like we could get away with just treating them as `script-src`, but if you think the capabilities warrant distinct treatment, `worklet-src` seems fine.

**Comment by mikewest** [comment]
We have `worker-src` because workers end up creating distinct execution contexts with their own globals, and potentially their own policy (in the case of `ServiceWorker` and `SharedWorker`).

If worklets have capabilities that mean developers may wish to restrict spinning up a worklet in ways that they wouldn't be worried about executing a normal script, or that allow them to bypass a page's policy by creating their own, then `worklet-src` might be reasonable.

My understanding of worklets, though, is that they're always going to be part of the context that created them. That is, they'll always have the same origin, secure contextness, active policies, etc. If that's the case, then they don't seem any different than scripts, and `script-src` seems reasonable.

**Comment by annevk** [comment]
I agree that just using `script-src` for now is fine.

**Comment by andypaicu** [comment]
I believe this issue can now be closed, unless there are further tests to be added than the ones I see above? I'll close it in a bit unless anyone complains.
