### ISSUE TITLE
Unable to parse IPv6 addresses in CSP source list

### ISSUE THREAD

**Issue by skateman** [w3c/webappsec-csp#224]
Due this it's impossible to enforce content security policies for WebSocket connections through IPv6 as an IPv6 address in the `connect-src` field is unparseable in all major browsers.

I was investigating the issue and traced it back to the [source list syntax in the CSP Level 2](https://www.w3.org/TR/CSP2/#source-list-syntax). I haven't found any traces of IPv6 address support in the grammar and so no browser actually implements this feature. There is however a mention that hosts should be favored over IP addresses in source expressions.

**Comment by andypaicu** [comment]
Only "127.0.0.1" will actually match anything because of its special significance. IPV4 addresses do match the grammar but that is only accidental and they won't actually match any host when it comes to allowing requests.
See the first note here: https://w3c.github.io/webappsec-csp/#framework-directive-source-list
And step 3 here: https://w3c.github.io/webappsec-csp/#match-hosts
