### ISSUE TITLE
Embedded: make clear that servers MUST respond with a CSP or Allow-CSP-From header, <meta> CSP's are not allowed.

### ISSUE THREAD

**Issue by dconnolly** [w3c/webappsec-csp#225]
For some static hosts (*cough* S3 *cough*) dynamic response headers or custom HTTP headers are not available, so they cannot serve `Content-Security-Policy` or `Allow-CSP-From` headers. Usually a CSP can be defined as `<meta http-equiv="Content-Security-Policy" content="...">`, but @mikewest indicates that the Chrome implementation does not respect the `<meta>` CSP, as that would require making a allowed/blocked decision after parsing the iframe'd document. 

The spec should make this clear: embedees MUST serve a `Content-Security-Policy` or `Allow-CSP-From` header, the `<meta>` header will not work unlike the general CSP case for a top-level document load.

**Comment by David263** [comment]
I've noticed that putting CSP headers into .htaccess files on Apache servers is rarely mentioned as a good way to make CSP apply to an entire website or a subset tree. It would be good to have published examples use .htaccess syntax, and to extend that syntax to a more structured form extending over multiple lines instead of being constricted to a single line.

This is a somewhat different issue from the unsuitabiluity of meta CSP elements, but I thought I'd mention it here as roughly in the same category. If there is general interest, I'll make this a standalone Issue.

**Comment by annevk** [comment]
I don't think we should mention particular server-side technology in the specification. There's nothing standard about `.htaccess`. That's best left for MDN and such.

**Comment by mikewest** [comment]
This issue was moved to w3c/webappsec-cspee#2
