### ISSUE TITLE
child-src still mentions to govern workers

### ISSUE THREAD

**Issue by ckerschb** [w3c/webappsec-csp#238]
CSP level 3 introduces the concept of the worker-src directive. While the description of worker-src [1] is up to date, the description of the child-src directive [2] still mentions to govern workers.

Action item:
Remove worker related text from child-src.

[1] https://www.w3.org/TR/CSP/#directive-worker-src
[2] https://www.w3.org/TR/CSP/#directive-child-src

**Comment by sideshowbarker** [comment]
If I’m not misunderstanding, I think it’s still the case that (for backward compatibility) the spec intentionally still requires the `child-src` to govern both nested browsing contexts  and workers.

The current spec at https://w3c.github.io/webappsec-csp/#directive-child-src has language which seems to make clear that `child-src` is deprecated but that the (legacy) requirements still apply:

> The `child-src` directive is deprecated. Authors who wish to regulate nested browsing contexts and workers SHOULD use the `frame-src` and `worker-src` directives, respectively.
>
> The `child-src` directive governs the creation of nested browsing contexts (e.g. `iframe` and `frame` navigations) and Worker execution contexts.

So incidentally I guess it’s also useful to mention that you pretty much always want to be reading the current spec at https://w3c.github.io/webappsec-csp/ when raising issues and such, and basically never reading the https://www.w3.org/TR/CSP/ spec—because you can’t trust that one to be up to date, as this case illustrates.

And that’s true in general for anything published under https://www.w3.org/TR — if a document published there has a link to a current version of the spec (_aka_ "Editor’s Draft"), then you always want to be reading that current version rather than the https://www.w3.org/TR  version.

**Comment by ckerschb** [comment]
I guess that makes sense in the end - thanks.

**Comment by mikewest** [comment]
1. I should spin an update to TR doc. Sorry about that confusion.
2. I shouldn't have to! We should automate it! I imagine the W3C has some sort of mystical autoupdating scripts somewhere that other folks are using, @sideshowbarker?

**Comment by sideshowbarker** [comment]
> I shouldn't have to! We should automate it! I imagine the W3C has some sort of mystical autoupdating scripts somewhere that other folks are using, @sideshowbarker?

Yes we do have now have an “autopublishing” mechanism that allows you to automatically publish a new version at https://www.w3.org/TR/CSP/ every time you push a change to the source at https://github.com/w3c/webappsec-csp/blob/master/index.src.html

And yes you should be using that I would be happy to help y’all get it set up. So let’s make time this week to do that.

Once that autopublishing mechanism is in place for the spec, the content of the documents at https://w3c.github.io/webappsec-csp/ and https://www.w3.org/TR/CSP/ then ends up being kept identical and up to date — at least until such time as you go to CR with it again

**Comment by dveditz** [comment]
> If I’m not misunderstanding, I think it’s still the case that (for backward compatibility) the spec intentionally still requires child-src to govern both nested browsing contexts and workers.

The spec is inconsistent. child-src still says it governs workers, but default-src and script-src say they are the fall-back for a missing worker-src (as does the "Changes from Level 2" section). Although more logical and predictable for people new to CSP, this breaks backwards compatibility and that should be stressed more in the spec.

We may want to special-case worker handling for the case where there is both a script-src (common!) and a deprecated child-src but no explicit worker-src. Have workers look for worker-src, child-src, _then_ script-src, default-src. But frames would still go frame-src, child-src, default-src.

That's even more confusing for workers, but at least won't be a backwards compatibility disaster of suddenly having workers governed by a script-src when they weren't before. Unless Google has numbers showing that it's not a problem in practice?
