### ISSUE TITLE
Ignoring Meta CSP if <script> tag appears before Meta CSP

### ISSUE THREAD

**Issue by ckerschb** [w3c/webappsec-csp#27]
Speculative loading is particularly challenging if a Meta CSP is present on a page, hence we (Mozilla) propose that Meta CSP should be simply ignored (log a warning to the console) if it appears after a `<script>` tag within the <head> portion of a document. Currently the spec states:
"Authors are strongly encouraged to place meta elements as early in the document as possible, because policies in meta elements are not applied to content which preceeds them."

In more detail, lets assume the following example:
```
 head
    script document.write("<!--") /script
    meta csp-stuff-here
 /head
 body
   I am still a comment. --> But I am not.
   img src="the-meta-csp-better-not-apply-here"
 /body
```

In the above example, the meta CSP policy would be applied to the preload, but not to the actual load. In a different scenario it's even worse. Let's assume:
```
head
  script document.write("<meta csp...>"); /script 
/head
body
  img src="foo.jpg"
```

In the above example, no CSP would be applied to the preload but to the actual load it would. I don't have to discuss what security implications this has. (Hopefully no sane web page author would ever do that, but who knows ...)

In addition, CSPs are additive, which means CSPs delivered through the header are merged with any Meta CSPs present on the page. Now one can assume that you can have all sorts of combinations, a CSP delivered through the header plus three meta CSPs where the second is commented out by document.write, etc. One can assume that this gets really messy and in our opinion not worth the effort, the implied slowdown for no security gain whatsoever.

We are open for discussions though!

*(Edited by @mozfreddyb: Added markdown syntax foo, because the web interface started swallowing stuff after the initial script tag)*

**Comment by mikewest** [comment]
That's not Chrome's existing behavior, though I understand that interaction with something like a preload scanner is complicated. We took the opposite approach for a while (that is, disabling the preload scanner if/when it saw a `<meta>` element containing a policy).

It's not clear why you'd only care about `<script>` though. What about `<link>`, for instance?

We say in the spec, basically, that the `<meta>` element's behavior is best-effort. Folks should use headers if they want guarantees. Ignoring a specified policy just because you might have made some requests that it would have blocked doesn't seem like a net win for the developer or user. *shrug*

**Comment by ckerschb** [comment]
As far as I am concerned it's mostly about document.write() which makes things complicated with the preload scanner. Hence dropping meta CSP after any appearance of a script tag sounded plausible.

But if I am interpreting your answer correctly, you would rather apply CSP to all the resources loaded after the meta CSP got parsed than to not apply it at all, right? Also sounds like an option even though I think it's a misleading one. If a browser incorrectly allows the preload but then blocks the actual load or vice versa. Nevertheless, you are absolutely right about the best-effort versus security guarantees tradeoff between meta and the header.

**Comment by michael-oneill** [comment]
Having the capability for dynamic CSP via a meta tag is important because it enables user control. 
You can have a base set of allowed resources then give the user the ability to reduce a supplementary se via an opt-int. This can be done now on Chrome, Edge, & Safari OSX by appending a metatag inside synchronously loaded script, we have an application that does that for e-privacy compliance in use now on  many sites in Europe.

Safety can  be ensured by also having a CSP in a header because the meta tag has to be as least as restrictive.

**Comment by bzbarsky** [comment]
> Having the capability for dynamic CSP via a meta tag is important

Even if it doesn't actually work reliably?

> appending a metatag inside synchronously loaded script

By which point various requests for things that come after that script in the source have already been kicked off.

I would really like to understand the actual guarantees people are expecting from meta CSP... not least because I expect them to end up different in different browsers due to different preloading setups, which seems quite suboptimal to me.

**Comment by michael-oneill** [comment]
It works in all the UAs that support it, for our use case. As long as subsequent disallowed script is not executed we are happy. For security we recommend a base CSP delivered by header also.

 

Mike

**Comment by bzbarsky** [comment]
OK, so you only care about script execution, not whether things are downloaded?

**Comment by michael-oneill** [comment]
I would prefer things to be not loaded, but I suppose that may be difficult in prefetch cases. Not executing the script is enough for my current use case.

 

Mike

**Comment by ckerschb** [comment]
Mozilla decided to implement meta csp using the best afford approach, which means that we are going to support doc.write(meta csp) with the down side that preloads might already have leaked information. (E.g. doc.write a meta csp using 'upgrade-insecure-requests' is not going to be applied to preloads). Thanks for all the feedback. I think that issue solved itself with that comment.
