### ISSUE TITLE
Prefetch-src are we allowed to use it yet?

### ISSUE THREAD

**Issue by ayumihamsaki** [w3c/webappsec-csp#302]
Hi,

I have seen the new "prefetch-src" found here: https://w3c.github.io/webappsec-csp/#directive-prefetch-src

However, when I go to the W3c webpage for CSP Level 3 found here: https://www.w3.org/TR/CSP3/

Is it not listed yet? 

Can we use it right now in our CSP or should we wait? Also will it be added to the main CSP W3c spec webpage?

Also, can we list preload resources in the prefetch-src or is it only for [resource-hints](https://w3c.github.io/resource-hints/)?

Thanks.

**Comment by dveditz** [comment]
Even if CSP3 were a finished standard ("Recommendation")--which it isn't--that wouldn't tell you which browsers support it yet. For this type of query you ask in a discussion group such as the mailing list mentioned at the top of the draft (public-webappsec@w3.org with subject line “[csp3] … message topic …” ).

Closing because this isn't an issue with the draft.
