### ISSUE TITLE
Consider applying both `child-src` and `script-src` to workers.

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec-csp#31]
@annevk suggested this in the Service Worker meeting when I complained about the algorithm in CSP. So let's think about that.

**Comment by igrigorik** [comment]
To clarify, this doesn't mean child-src would be removed? Making worker fetch be an intersection of these seems a bit weird.. what if you have an origin from which only workers are allowed?

**Comment by annevk** [comment]
Workers are same-origin.

**Comment by arturjanc** [comment]
It looks like this might become more important due to the addition of markup-based ways to add SWs, such as link#rel=serviceworker: https://bugs.chromium.org/p/chromium/issues/detail?id=582310

With the ability to inject SWs this way, there's a potential that previously safe CSPs (e.g. those which specify empty or locked-down script-src and object-src) will suddenly become ineffective -- attackers who can inject markup might be able to add SWs and end up with a full XSS despite the CSP. Making SWs respect script-src sounds like a good way to solve this.

**Comment by arturjanc** [comment]
BTW, something that is worth putting thought into is how this would interact with nonce-based CSP policies, e.g. those using `'unsafe-dynamic'`. For example, assume we have:
`Content-Security-Policy: script-src: 'nonce-foo' 'unsafe-dynamic'; child-src: 'self';`

Under which conditions should a Service Worker from [self]/foo.js be loaded?
- For `<link rel="serviceworker" href="/foo.js">` would we need to add a nonce attribute?
- For SWs registered with the JS API, is there anything the developer would have to do?

I assume that for regular nonce-based policies (e.g. script-src 'self' 'nonce-foo') both ways to register SWs would be okay as long as one of the script-src and child-src source directives matches the SW location.

**Comment by mikewest** [comment]
We've revamped this as described in #146.
