### ISSUE TITLE
Proposal: Add report field to signal if a violation was triggered by a browser extension

### ISSUE THREAD

**Issue by ureesoriano** [w3c/webappsec-csp#450]
Taking a couple of steps back, the intent of CSP reports is to allow us to **infer whether or not our CSP blocked attempts to load legitimate resources**.

But, how we browse the web has changed quite a bit since CSP was first introduced: Anyone managing a site's CSP has encountered the humongous amount of **noise caused by browser extensions.**

The problem I see is that we try to infer if a violation was triggered by an extension or by our site by looking at the data on the CSP reports (which often is insufficient for that purpose).
But, **the browser** that sends the report in the first place **is in a much better position to determine that**.

**Suggestion:** Add a field to CSP reports to signal if a violation was triggered by a browser extension.

--------

*Note: I am aware that this might be a far-fetched and even naive suggestion. I lack a significant amount of context, and I am not sure if this is feasible. My apologies if that is the case.*

**Comment by koto** [comment]
The intention is for the CSP to allow browser extensions to bypass the CSP and not trigger violations at all, as outlined in https://w3c.github.io/webappsec-csp/#extensions. Practically, it's difficult for the browsers to determine that the code violating the CSP was injected by the extension, hence the noise. But if the browsers were able to distinguish the regular injections from extension injections, they would simply not block the latter, instead of annotating them in violation reports.

**Comment by ureesoriano** [comment]
Thanks for the explanation, @koto !  
The approach you describe tackles the issue from a much better approach.  
Unfortunately, and as you point, it won't be easy for browsers to implement that.
