### ISSUE TITLE
CSP: connect-src 'self' and websockets

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec-csp#7]
_From @klings on September 28, 2015 19:25_

Declaring a CSP with connect-src ‘self’ will not allow websockets back to the same host/port, since they're not same origin. This might come as a surprise to developers that haven't studied the CSP specification in detail and have a firm grasp of the same origin security model.

One option could be to add a note to the spec to clarify that this is the intended behaviour. Another option could be to make an exception for connect-src 'self', and allow ws(s): requests to same host/port.

I'm not sure what the security implications could be of the latter, but it might be worth some consideration. 

_Copied from original issue: w3c/webappsec#489_

**Comment by zdexter** [comment]
I'm not sure this is intended behavior - what about the "load web page in browser, then make websocket connection" use case? This is a very common use case... see https://github.com/w3c/webappsec/issues/506 for more.

**Comment by mikewest** [comment]
Poked at this in https://github.com/w3c/webappsec-csp/commit/0e81d81b64c42ca3c81c048161162b9697ff7b60, WDYT?

**Comment by klings** [comment]
Thanks for looking into this! This should do the trick for same host/port web sockets.

**Comment by adrianmacneil** [comment]
Would it also be possible to support `ws:` if the current protocol is `http:` and the CSP allows `self`? It sounds like as written `self` will only support `wss:` if the current page was served via http.

**Comment by thapet** [comment]
This seems still to be an issue - like amacneil described. I have tried with connect-src 'self', but ws request to same origin (host and port) does not work (when testing from remote machine).
I have tried with Chrome v.59 and Edge v.14.

**Comment by annevk** [comment]
Reopening this per recent comments. It seems this wasn't fixed properly yet.

**Comment by emilfihlman** [comment]
Issue opened at: https://bugs.chromium.org/p/chromium/issues/detail?id=815142

**Comment by emilfihlman** [comment]
New development https://bugs.chromium.org/p/chromium/issues/detail?id=815142#c8

**Comment by Thesephi** [comment]
Sincere apologies if I'm asking in a wrong thread, but I think Safari also has the same issue as specified in [a previous comment](https://github.com/w3c/webappsec-csp/issues/7#issuecomment-307014294) by thabet (although I tested with `https` & `wss`) (I tested on Safari `12.1.1` and Safari Technology Preview `Release 87 (Safari 13.0, WebKit 14608.1.33.1)`). Internet search didn't result in productive findings, so I decided to ask here. Could anyone else reproduce?

![wss_https_safari](https://user-images.githubusercontent.com/2597375/61049126-faac2480-a3e3-11e9-9b1f-6bc3cf32e233.png)

**Comment by Malvoz** [comment]
Note that @mikewest intended to close this issue in https://github.com/w3c/webappsec-csp/commit/0e81d81b64c42ca3c81c048161162b9697ff7b60:

> Fixes w3c/webappsec#7.

"Fixes" was pointed to webappsec#7 and not webapp**sec**-csp#7.

<hr>

Per @Thesephi's and @thapet's comments I think it'd be good if we could track implementations in those browsers..

**Comment by ratiofu** [comment]
@Thesephi I can reproduce in Safari `12.1.2` with CSP `connect-src 'self'`. In fact, because of that error, I landed here. I filed [WebKit bug 201591](https://bugs.webkit.org/show_bug.cgi?id=201591)

**Comment by MoxxiManagarm** [comment]
I just came here because of the same. Still reproducable with Safari 13. Other browser accept wss to self with connect-src 'self' defined.

**Comment by mikewest** [comment]
I believe the spec is correct, and covered by https://wpt.fyi/results/content-security-policy/connect-src/connect-src-websocket-self.sub.html?label=experimental&label=master&aligned. Closing this out again, as the bug against WebKit is the right place to comment on priority.

/cc @johnwilander

**Comment by mkurz** [comment]
There is finally work going on to get this fixed in Safari: https://bugs.webkit.org/show_bug.cgi?id=235873 (before it was https://bugs.webkit.org/show_bug.cgi?id=201591, which was marked as duplicate)

**Comment by mkurz** [comment]
https://bugs.webkit.org/show_bug.cgi?id=235873 is finally resolved now, so this should be fixed in the next Safari release 16 (maybe even 15.5 or 15.6 if those will happen)

**Comment by silverwind** [comment]
Maybe it's a regression but I do observe this exact issue in Firefox 120.0b9 where `connect-src: self` does not allow `wss://localhost` when origin is `https://localhost`.

**Comment by mkurz** [comment]
@silverwind I think you should report that to the firefox bug tracker?

**Comment by silverwind** [comment]
I will if I reproduce again. Strangely enough downgrading and upgrading Firefox seems to have resolved it for now.

**Comment by skyzyx** [comment]
I spent way too much time today going spelunking through issues and patch notes this morning.

The [WPT test](https://wpt.fyi/results/content-security-policy/connect-src/connect-src-websocket-self.sub.html) for this was added in September 2018.

* It was already fixed in Firefox Dev and Stable. [[source](https://wpt.fyi/results/content-security-policy/connect-src/connect-src-websocket-self.sub.html?label=experimental&label=master&max-count=1&to=2018-09-19T00%3A00%3A00.000Z)] (September 2018)

* It was fixed in Chrome 71.0.3559.6 (Dev) when it was announced on the Chrome blog (commit `15b59a4d4fe5524b5cb006747831aa1c47012e75`). [[source](https://chromium.googlesource.com/chromium/src/+log/71.0.3554.4..71.0.3559.6?pretty=fuller&n=10000), [source](https://wpt.fyi/results/content-security-policy/connect-src/connect-src-websocket-self.sub.html?label=experimental&label=master&max-count=1&to=2018-09-27T00%3A00%3A00.000Z)] (September 2018)

* It was fixed in WebKit [r292266](https://trac.webkit.org/changeset/292266/webkit/), which was released in Safari Technology Preview 144, although it didn't make the release notes until 145 was released a week later [[source](https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-145#Content-Security-Policy), [source](https://wpt.fyi/results/content-security-policy/connect-src/connect-src-websocket-self.sub.html?label=experimental&label=master&max-count=1&to=2022-05-04T00%3A00%3A00.000Z)] (May 2022)

* That WebKit fix made it into Safari 16.0. [[source](https://wpt.fyi/results/content-security-policy/connect-src/connect-src-websocket-self.sub.html?label=stable&label=master&max-count=1&to=2022-09-14T00%3A00%3A00.000Z)] (September 2022)

* Edge 17 (EdgeHTML) already had support when the test was written. It inherited that support when adopting Chromium in 2019.

* With Opera switching to Chromium in 2013, I would assume that it received patches from upstream Chromium (September 2018) when that bug was fixed. (It is not tested as part of the WPT test suite.)
