### ISSUE TITLE
Allow `hash-source` expressions match integrity metadata for external scripts.

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec-csp#78]
Currently, `script-src 'sha256-qznLcsROx4GACP2dm0UCKCzCG+HiZ1guq6ZZDob/Tng='` matches `<script>alert('Hello, world.');</script>`. It does not match `alert('Hello, world.');` in a non-inlined script.

I'd suggest that we alter this behavior to allow matching external scripts which assert integrity metadata about the resource requested. That is, the above directive could match:

``` html
<script src="/hello.js"
        integrity="qznLcsROx4GACP2dm0UCKCzCG+HiZ1guq6ZZDob/Tng="
        crossorigin="anonymous">
```

As discussed on the 20.4.2016 call, this could allow some interesting loader functionality in combination with `'unsafe-dynamic'`.

/cc @hillbrad @dveditz 

(Note: Specifying this cleanly depends a bit on https://github.com/w3c/webappsec-subresource-integrity/issues/31.)

**Comment by mikewest** [comment]
I took a first pass at this in https://github.com/w3c/webappsec-csp/commit/a299d38d1b54e3d9612d11fb69cc8174b5e44051. WDYT. @hillbrad and SRI folks (@metromoxie, @fmarier, @mozfreddyb, @devd)?

**Comment by devd** [comment]
hmm .. combining with existing hash-src means that using sri hash to whitelist script resource would disable inline scripts? that seems weird.

**Comment by mikewest** [comment]
Hrm. This doesn't change the behavior of existing pages. You can still whitelist SRI'd script elements by URL, for example.

Are you suggesting adding a new hash type (`external-[algorithm]-[digest]`) instead?

**Comment by devd** [comment]
I thought this was to fix the CDN trust issue. For example, I can remove the jquery CDN from my source whitelist and add the hash instead and it will just load fine?

And yes, I like a new hash type instead. Still curious about backwards compat.

**Comment by fmarier** [comment]
Sites that use static HTML files (e.g. blogs using static site generators and hosted on GitHub) will require this features in order to load external resources in the brave new `strict-dynamic` world.

**Comment by fmarier** [comment]
I like how the algorithm currently works in the editor's draft.

Given a CSP policy of `script-src 'sha256-123456'`, the following would be true:

- `<script src="..." integrity="sha3000-abcde sha256-123456">`: blocked ('abcde' hash not approved)
- `<script src="..." integrity="invalid">`: blocked (no matching hashes)

which makes sense to me. We should also define the following:

- `<script src="..." integrity="invalid sha256-123456">`: blocked ('invalid' option not allowed)

Essentially, we would forbid SRI options for now, which I think is reasonable given that any future options could interact in a bad way with CSP.

The one corner case that feels weird is that given a CSP policy of "script-src 'sha3000-123456'", we would have this:

- `<script src="..." integrity="sha3000-abcde">`: allowed (SRI checks are skipped)

While less than ideal, I guess it's up to the author to provide enough hash algorithms so that all browsers will perform SRI checks. This is an existing issue with SRI, so I'm not concerned that it would also carry over to CSP.

**Comment by fmarier** [comment]
So I guess all that's missing from the CSP spec is that any non-hash tokens in the `integrity` attribute should make the CSP checks fail.

**Comment by oreoshake** [comment]
I hate to leave a :+1: comment but this is such a natural extension for those using SRI that implementing this was a ~2 line change for our code base.

**Comment by oreoshake** [comment]
Also, the text lgtm but I am not a spec author :smile:

**Comment by devd** [comment]
@fmarier maybe I am missing something, but isn't the check against CSP only done after [parse metadata](https://www.w3.org/TR/SRI/#parse-metadata). If browser doesn't support sha3000 algorithm, the parsing will return "no metadata" and CSP will not whitelist the load. 

(I am actually slightly worried about a backwards compat case: as an algorithm gets deprecated by a new useragent, how will app authors need to update their CSP policy and integrity metadata to work with both old and new browsers).

**Comment by fmarier** [comment]
> maybe I am missing something, but isn't the check against CSP only done after parse metadata. If browser doesn't support sha3000 algorithm, the parsing will return "no metadata" and CSP will not whitelist the load.

Let's look at two examples. Given a CSP policy of `script-src 'sha3000-abcde' 'sha256-123456'` and the following element:

    <script src="..." integrity="sha3000-abcde sha256-123456">

We intend to allow this load because all of the hashes in the `integrity` attribute are whitelisted by the CSP. When we run SRI's `parseMetadata` on `sha3000-abcde sha256-123456`, we only get `sha256-123456` and that is present in the CSP, so the load is allowed. All good.

If on the other hand, we have the same policy and then the following element:

    <script src="..." integrity="sha3000-abcde">

then it's unclear what would happen. The `parseMetadata` algorithm will return an empty list (different from `no metadata`) and the SRI load would normally proceed assuming correct CORS usage.

If we want to allow this in CSP, we should rephrase the note to read:

> the request will match a policy’s hash-sources if and only if each item **returned by applying the SRI parseMetadata algorithm over the script's integrity metadata** matches the policy.

If we want CSP to block these loads, then we could say something like:

> the request will match a policy’s hash-sources if and only if each item returned by applying the SRI parseMetadata algorithm over the script's integrity metadata matches the policy **and that at least one item is returned by parseMetadata**.

**Comment by devd** [comment]
hmm .. that seems like the right behavior. SRI allows it, but CSP will block it unless the source is whitelisted by the script-src whitelist.

**Comment by mikewest** [comment]
@devd, @fmarier: I think the patch in https://github.com/w3c/webappsec-csp/commit/68aecb5003b0081afcc4f70524b81f8b381aa97c does what you'd like. Mind taking a look before I close this out?

**Comment by devd** [comment]
yeah looks good.
