### ISSUE TITLE
CSP Violation Reports for redirects should include full original URI and origins in the redirect URIs

### ISSUE THREAD

**Issue by devd** [w3c/webappsec-csp#86]

**Comment by mikewest** [comment]
Sorry, I missed this too. (You'll be seeing that a lot, I think, since TPAC is a nice forcing-function to make me realize that I've done a bad job staying on top of things here...)

The reporting changes were meant to make it less likely that we leak information that the page doesn't itself have access to. We can prevent explicitly leaking the origin of a redirect target, so why shouldn't we?

**Comment by devd** [comment]
not sure what you mean: I was saying if <iframe src="/foo?weirdarg=blah"> or <iframe src="allowdsite.com/foobar"> redirects to "notallowed.com/bar", then I should at least know that the violation was caused by /foo?weirdarg=blah or allowedsite.com/foobar. This is something that I am already allowed to learn if they are both disallowed by policy, I think

**Comment by mikewest** [comment]
Yeah, if `<iframe src="allowdsite.com/foobar">` redirects to `disallowed.com`, then you should get a report that says `child-src` was violated by a request to `allowedsite.com/foobar`. I think that's what the spec says today.

**Comment by andypaicu** [comment]
I believe the spec now covers this indeed.
