### ISSUE TITLE
CSP2: copy/paste bug in `default-src` definition.

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec-csp#9]
_From @mikewest on September 22, 2015 17:13_

> Let the default sources be the result of parsing the default-src directive’s value as a source list if a default-src directive is explicitly specified, and otherwise the U+002A ASTERISK character (*).

This is a copy/paste error on my part. A missing `default-src` should have no effect; as written, it would block inline script and eval.

_Copied from original issue: w3c/webappsec#481_

**Comment by mikewest** [comment]
Not in CSP1, really just an error on my part: http://www.w3.org/TR/2012/CR-CSP-20121115/#default-src

@hillbrad / @wseltzer: Let me guess. We'll need to go back through CR to fix this?

**Comment by mikewest** [comment]
_From @hillbrad on September 22, 2015 17:31_

I would say this is a correction that does not need a new feature, (indeed,
it specifies continuity of behavior with already specified behavior which
has gone through multiple exclusion periods) so perhaps we can get the
Director's approval to amend the CR without triggering an new exclusion
period?

**Comment by mikewest** [comment]
Actually, looking at this again, I don't think it has any impact. We're not "enforcing" the `default-src` directive if it's not present in the list of directives, so the value doesn't matter at all. Specifying that it's the `*` character makes no sense, but it's not actively harmful.

**Comment by michaelficarra** [comment]
> We're not "enforcing" the `default-src` directive if it's not present in the list of directives

I believe that is true, and it actually exposes a much deeper problem with the specification. At first, I thought this statement would be wrong since, for instance, `script-src` uses "default sources" as "allowed script sources" if the `script-src` directive is not present (section 7.15). But now I see that the directive is *never even enforced* if it is not present (section 5). So the entire concept of default sources is unused. Should I open a separate issue for this?

Anyway, assuming the above problem is fixed, the default sources should be used during the enforcement of `script-src` and `style-src` directives, so it should matter what the default sources are in absence of a `default-src` directive.

**Comment by mikewest** [comment]
1. This hope this will be significantly clearer in CSP3, which I'm working on at https://w3c.github.io/webappsec-csp/.

2. When `default-src` is enforced, all the `*-src` directives are enforced. This is hand-wavingly spelled out in http://www.w3.org/TR/CSP2/#directive-default-src. This should mean that things are wired up to the extent that CSP2 wires anything up.

**Comment by michaelficarra** [comment]
Okay, I'm convinced by that. I saw that directive list in 7.4, but for some reason it didn't click for me until you spelled it out.

**Comment by mikewest** [comment]
Sorry. You're entirely correct that the specification is vague to the point of being obtuse. I'd appreciate feedback on CSP3, which is more or less a complete rewrite in the hopes of explaining the model.
